package com.abhiram.databeatassessment.core.util

enum class CountryData(
    val countryFlag: String,
    val displayText: String,
    val countryCodeAlpha2: String?,
) {
    World("🌐", "World", null),
    Argentina("🇦🇷", "Argentina", "ar"),
    Australia("🇦🇺", "Australia", "au"),
    Austria("🇦🇹", "Austria", "at"),
    Belgium("🇧🇪", "Belgium", "be"),
    Brazil("🇧🇷", "Brazil", "br"),
    Bulgaria("🇧🇬", "Bulgaria", "bg"),
    Canada("🇨🇦", "Canada", "ca"),
    China("🇨🇳", "China", "cn"),
    Colombia("🇨🇴", "Colombia", "co"),
    Cuba("🇨🇺", "Cuba", "cu"),
    CzechRepublic("🇨🇿", "Czech Republic", "cz"),
    Egypt("🇪🇬", "Egypt", "eg"),
    France("🇫🇷", "France", "fr"),
    Germany("🇩🇪", "Germany", "de"),
    Greece("🇬🇷", "Greece", "gr"),
    HongKong("🇭🇰", "Hong Kong", "hk"),
    Hungary("🇭🇺", "Hungary", "hu"),
    India("🇮🇳", "India", "in"),
    Indonesia("🇮🇩", "Indonesia", "id"),
    Ireland("🇮🇪", "Ireland", "ie"),
    Israel("🇮🇱", "Israel", "il"),
    Italy("🇮🇹", "Italy", "it"),
    Japan("🇯🇵", "Japan", "jp"),
    Latvia("🇱🇻", "Latvia", "lv"),
    Lithuania("🇱🇹", "Lithuania", "lt"),
    Malaysia("🇲🇾", "Malaysia", "my"),
    Mexico("🇲🇽", "Mexico", "mx"),
    Morocco("🇲🇦", "Morocco", "ma"),
    Netherlands("🇳🇱", "Netherlands", "nl"),
    NewZealand("🇳🇿", "New Zealand", "nz"),
    Nigeria("🇳🇬", "Nigeria", "ng"),
    Norway("🇳🇴", "Norway", "no"),
    Philippines("🇵🇭", "Philippines", "ph"),
    Poland("🇵🇱", "Poland", "pl"),
    Portugal("🇵🇹", "Portugal", "pt"),
    Romania("🇷🇴", "Romania", "ro"),
    Russia("🇷🇺", "Russia", "ru"),
    SaudiArabia("🇸🇦", "Saudi Arabia", "sa"),
    Serbia("🇷🇸", "Serbia", "rs"),
    Singapore("🇸🇬", "Singapore", "sg"),
    Slovakia("🇸🇰", "Slovakia", "sk"),
    Slovenia("🇸🇮", "Slovenia", "si"),
    SouthAfrica("🇿🇦", "South Africa", "za"),
    SouthKorea("🇰🇷", "South Korea", "kr"),
    Sweden("🇸🇪", "Sweden", "se"),
    Switzerland("🇨🇭", "Switzerland", "ch"),
    Taiwan("🇹🇼", "Taiwan", "tw"),
    Thailand("🇹🇭", "Thailand", "th"),
    Turkey("🇹🇷", "Turkey", "tr"),
    UnitedArabEmirates("🇦🇪", "United Arab Emirates", "ae"),
    UnitedKingdom("🇬🇧", "United Kingdom", "gb"),
    UnitedStates("🇺🇸", "United States", "us"),
    Venezuela("🇻🇪", "Venezuela", "ve"),
}